### ISSUE TITLE
my manual is not showing 

### ISSUE THREAD

**Issue by v3n0m30** [d7omdev/ags#1]
![2024-11-24_07-15](https://github.com/user-attachments/assets/04d094cb-df1b-4ba1-af86-f971eb8288e7)
 

and bro the brightness is also not loading 

and bro the SUPER + / is not working bro for the manual

**Comment by d7omdev** [comment]
Thats by design, i made the battery module disappear if the battery is at 100% to save space and make the bar more cleaner 

For the cheatsheet that because you have one monitor, i already answered this follow [this comment](https://www.reddit.com/r/unixporn/s/Pi5eMD9niK) and it'll work for you

**Comment by v3n0m30** [comment]
ohk bro thanks it working just wanna know can i add more to the witget like that swap is doing nothing for more will like somthing like network monitor instead and bro will like to know how you made you windows small like you terminal like when i call mine it just open in the whole screen

**Comment by d7omdev** [comment]
You need to understand the code structure to add modules but the bar modules are loaded in the `~/.config/ags/modules/bar/main.js` file.
